import { useState } from 'react';
import type { FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import CryptoJS from 'crypto-js';
import JSEncrypt from 'jsencrypt';
import { createEmployee } from '../api';

export default function RegisterPage() {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    HOTEN: '',
    EMAIL: '',
    TENDN: '',
    MATKHAU: '',
  });
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [loading, setLoading] = useState(false);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError('');
    setSuccess('');
    setLoading(true);

    try {
      const hashedPassword = CryptoJS.SHA1(formData.MATKHAU).toString(CryptoJS.enc.Hex);

      const crypt = new JSEncrypt({ default_key_size: '2048' });
      crypt.getKey();
      const pubKey = crypt.getPublicKey();
      const privKey = crypt.getPrivateKey();

      // Mã hóa Private Key bằng AES với mật khẩu gốc của user
      const encryptedPrivKey = CryptoJS.AES.encrypt(privKey, formData.MATKHAU).toString();

      // Gửi ENC_PRIVKEY lên server để lưu vào DB (cũng lưu vào localStorage để dùng ngay)
      const res = await createEmployee(null, {
        HOTEN: formData.HOTEN.trim(),
        EMAIL: formData.EMAIL.trim(),
        LUONG: null,
        TENDN: formData.TENDN.trim(),
        MK: hashedPassword,
        PUBKEY: pubKey,
        ENC_PRIVKEY: encryptedPrivKey,
      });

      const createdManv = res?.manv ?? null;
      if (createdManv) {
        localStorage.setItem(`lab4_encrypted_privkey_${createdManv}`, encryptedPrivKey);
        setSuccess(`Đăng ký tài khoản thành công. Mã nhân viên của bạn là ${createdManv}. Vui lòng ghi lại mã này và dùng để đăng nhập.`);
      } else {
        setSuccess('Đăng ký tài khoản thành công. Vui lòng đăng nhập để sử dụng hệ thống.');
      }
      setFormData({ HOTEN: '', EMAIL: '', TENDN: '', MATKHAU: '' });
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Đăng ký thất bại.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="login-container">
      <div className="login-card register-card">
        <div className="login-header">
          <h1>Đăng Ký</h1>
          <p>Tài khoản nhân viên</p>
        </div>

        <form onSubmit={handleSubmit} className="login-form">
          {/* MANV is auto-generated by the system; user must not enter it */}

          <div className="form-group">
            <label htmlFor="hoten">Họ Tên</label>
            <input
              id="hoten"
              type="text"
              value={formData.HOTEN}
              onChange={(e) => setFormData((prev) => ({ ...prev, HOTEN: e.target.value }))}
              placeholder="Nhập họ tên"
              required
              disabled={loading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              id="email"
              type="email"
              value={formData.EMAIL}
              onChange={(e) => setFormData((prev) => ({ ...prev, EMAIL: e.target.value }))}
              placeholder="Nhập email"
              required
              disabled={loading}
            />
          </div>

          {/* Lương cơ bản do Admin nhập; không hiển thị cho người đăng ký */}

          <div className="form-group">
            <label htmlFor="tendn">Tên Đăng Nhập</label>
            <input
              id="tendn"
              type="text"
              value={formData.TENDN}
              onChange={(e) => setFormData((prev) => ({ ...prev, TENDN: e.target.value }))}
              placeholder="Nhập tên đăng nhập"
              required
              disabled={loading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="matkhau">Mật Khẩu</label>
            <div className="password-field">
              <input
                id="matkhau"
                type={showPassword ? 'text' : 'password'}
                value={formData.MATKHAU}
                onChange={(e) => setFormData((prev) => ({ ...prev, MATKHAU: e.target.value }))}
                placeholder="Nhập mật khẩu"
                required
                disabled={loading}
              />
              <button
                type="button"
                className="password-visibility-btn"
                onClick={() => setShowPassword((prev) => !prev)}
                disabled={loading}
                aria-label={showPassword ? 'Ẩn mật khẩu' : 'Hiện mật khẩu'}
                title={showPassword ? 'Ẩn mật khẩu' : 'Hiện mật khẩu'}
              >
                {showPassword ? (
                  <svg viewBox="0 0 24 24" aria-hidden="true">
                    <path d="M3 3l18 18" />
                    <path d="M10.6 10.6a2 2 0 002.8 2.8" />
                    <path d="M9.88 5.09A9.77 9.77 0 0112 4c5.5 0 9.5 4.5 10 8-.18 1.18-.77 2.47-1.7 3.67" />
                    <path d="M6.61 6.61C4.37 8.03 2.57 10.2 2 12c.5 3.5 4.5 8 10 8a9.6 9.6 0 005.39-1.61" />
                  </svg>
                ) : (
                  <svg viewBox="0 0 24 24" aria-hidden="true">
                    <path d="M2 12s3.5-8 10-8 10 8 10 8-3.5 8-10 8S2 12 2 12z" />
                    <circle cx="12" cy="12" r="3" />
                  </svg>
                )}
              </button>
            </div>
          </div>

          {error && <div className="form-error">{error}</div>}
          {success && <div className="form-success">{success}</div>}

          <button type="submit" className="login-btn" disabled={loading}>
            {loading ? 'Đang xử lý...' : 'Đăng Ký'}
          </button>

          <button type="button" className="login-link-btn" onClick={() => navigate('/')} disabled={loading}>
            Quay lại đăng nhập
          </button>
        </form>
      </div>
    </div>
  );
}
